### ISSUE TITLE
update publications.html automatically

### ISSUE THREAD

**Issue by tjhei** [dealii/website#4]
We currently manually added output.html from
https://ci.tjhei.info/job/publication-list/job/master/lastSuccessfulBuild/artifact/output.html

**Comment by bangerth** [comment]
When there, we should also expose the different sections of the page to mkdocs so that it can show a next-level-down set of links in the menu on the left.

**Comment by tjhei** [comment]
yes, I will work on that.

**Comment by tjhei** [comment]
ping @tamiko

**Comment by tamiko** [comment]
@tjhei on it

**Comment by tamiko** [comment]
@tjhei I would like to minimize the amount of cronjobs/services needed in order to piece together the website. So let's quickly discuss some alternatives to wget'ting the file on the server. What about we add a fine-grained access token to the website repository so that your update script that is currently creating `output.html` simply updates the file in the website repository directly? (For example by creating a pull request and then merging it.)
